I18n
KeyJ148/tow pull request #171
Opened 2023-03-19 17:32 UTC by Bronuh

2023-03-19 17:50 UTC, KeyJ148 requested changes

2023-03-19 17:50 UTC, KeyJ148 commented on gradlew
Вот это изменение откати обратно, остальные изменения прав скорее полезны

2023-03-19 17:50 UTC, KeyJ148 commented on OrchEngine/src/main/java/cc/abro/orchengine/services/LocalizationService.java
> + * <b style="color: red;">Потом допилю, не плачь</b>
😢

2023-03-19 17:50 UTC, KeyJ148 commented on OrchEngine/src/main/java/cc/abro/orchengine/services/LocalizationService.java
> +	private ArrayList<Localization> locales = new ArrayList<>();
Лучше `private final List<Localization> locales = new ArrayList<>();`

2023-03-19 17:50 UTC, KeyJ148 commented on OrchEngine/src/main/java/cc/abro/orchengine/services/LocalizationService.java
> +	private static final String DEFAULT_LOCALE = """
Вот эту штуку не очень понял. Её выпилем как только создам файл с конкретной локализацией?

2023-03-19 17:50 UTC, KeyJ148 commented on OrchEngine/src/main/java/cc/abro/orchengine/services/LocalizationService.java
> +		// Где-то тут должны сканироваться и собираться локали. Потом прикрутим, главное шоб работало.
Этот кусок есть у @Rumrie, я ему объяснял как это правильно сделать

2023-03-19 17:50 UTC, KeyJ148 commented on OrchEngine/src/main/java/cc/abro/orchengine/services/LocalizationService.java
> +	public ArrayList<String> getlocales(){
Возвращать лучше просто List<String>

2023-03-19 17:50 UTC, KeyJ148 commented on OrchEngine/src/main/java/cc/abro/orchengine/services/LocalizationService.java
> +		ArrayList<String> localeIds = new ArrayList<>();
Если ты хочешь вернуть массив, но так чтобы пользователь функции не смог поменять элементы в массиве, то можешь сделать Collections.createUnmodificatedList(list)

2023-03-19 17:50 UTC, KeyJ148 commented on OrchEngine/src/main/java/cc/abro/orchengine/services/LocalizationService.java
> +			currentLocale = locales.stream().filter(l -> Objects.equals(l.id, id)).findFirst().get();
В принципе можно было хранить данные в Map<String, Localization>

2023-03-19 17:50 UTC, KeyJ148 commented on OrchEngine/src/main/java/cc/abro/orchengine/services/LocalizationService.java
> +	public String localize(String key, Object... args){
🔥

2023-03-19 17:50 UTC, KeyJ148 commented on OrchEngine/src/main/java/cc/abro/orchengine/services/LocalizationService.java
> +	// TODO: А че, обязательно весь сервис писать одним классом/файлом? Куда это всё выносить если нет?
В отдельный класс, конечно
Можешь и сервис и класс Localzation положить в cc.abro.orchengine.resources.locales

2023-03-19 17:50 UTC, KeyJ148 commented on OrchEngine/src/main/java/cc/abro/orchengine/services/LocalizationService.java
> +			String localizedString = localeMap.get(key);
У мапы есть функция  getOrDefault() на случай null

2023-03-19 17:50 UTC, KeyJ148 commented on OrchEngine/src/main/java/cc/abro/orchengine/services/LocalizationService.java
> +			String localizedString = localeMap.get(key);
У мапы есть функция  getOrDefault() на случай null
Туда можно запихать как значение, так и лямбду pseudolocalize(key)

2023-03-19 17:50 UTC, KeyJ148 commented on OrchEngine/src/main/java/cc/abro/orchengine/services/LocalizationService.java
> +			String localizedString = localeMap.get(key);
У мапы есть функция  getOrDefault() на случай null
Туда можно запихать как значение, так и лямбду pseudolocalize(key)

2023-03-19 17:50 UTC, KeyJ148 commented on OrchEngine/src/main/java/cc/abro/orchengine/services/LocalizationService.java
> +				// TODO: потом обработаю (нет)
В лог запищи хотя бы
Да и при успешной загрузке в лог пиши
И при пвсевдолокализации, когда ключ не найден

2023-03-19 18:44 UTC, Bronuh commented on OrchEngine/src/main/java/cc/abro/orchengine/services/LocalizationService.java
> +	private static final String DEFAULT_LOCALE = """
Да, эта штука только для тестирования

2023-03-19 18:44 UTC, Bronuh commented on OrchEngine/src/main/java/cc/abro/orchengine/services/LocalizationService.java
> +	public String localize(String key, Object... args){
Да не ты, а нормальный ключ

2023-03-19 18:44 UTC, Bronuh commented on OrchEngine/src/main/java/cc/abro/orchengine/services/LocalizationService.java
> +				// TODO: потом обработаю (нет)
Если мы всю псевдолокализацию в лог писать будем, то у нас утечка памяти будет не только в оперативе, но и на диске

2023-03-20 05:48 UTC, KeyJ148 commented on gradlew
> -#!/usr/bin/env sh
Мне кажется или права всё еще 644 ?

2023-03-20 06:18 UTC, KeyJ148 commented on OrchEngine/src/main/java/cc/abro/orchengine/resources/locales/Localization.java
> +			log.warn("Unable to load locale from props code");
Добавь плиз инфу для поиска проблемы: id/name, code

2023-03-20 06:18 UTC, KeyJ148 commented on OrchEngine/src/main/java/cc/abro/orchengine/resources/locales/Localization.java
> +	private Map<String, String> localeMap = new HashMap<>();
Тоже можно final объявить

2023-03-20 06:18 UTC, KeyJ148 commented on OrchEngine/src/main/java/cc/abro/orchengine/resources/locales/LocalizationService.java
> +	// private final List<Localization> locales = new ArrayList<>();
Закомменченный код

2023-03-20 07:15 UTC, Bronuh commented on OrchEngine/src/main/java/cc/abro/orchengine/resources/locales/Localization.java
> +			log.warn("Unable to load locale from props code");
Ладно code и name, а id откуда брать, если его отсутствие и является одной из главных ошибок после ошибки парсинга?

2023-03-20 07:30 UTC, KeyJ148 commented on OrchEngine/src/main/java/cc/abro/orchengine/services/LocalizationService.java
> +				// TODO: потом обработаю (нет)
Ну в логах можно настроить ротацию логов, чтобы они сами очищались.
В целом норм практика писать в лог о проблемах с локализацией. Это должны быть редкие и единичные случаи, когда локализация продолбана.

2023-03-20 07:32 UTC, KeyJ148 commented on OrchEngine/src/main/java/cc/abro/orchengine/resources/locales/Localization.java
> +			log.warn("Unable to load locale from props code");
Ну заюзай getId(), а если он null, то так и пиши -- будем знать, что онnull

2023-03-20 07:34 UTC, KeyJ148 approved these changes
Огнище.

2023-03-20 08:22 UTC, merged